name: tufterati
channels:
  - default
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.4
  - ipython=7.8
  - ipdb=0.12
  - pylint=2.4
  - pytest=5.2
  - dash=1.4
  - dash-daq=0.2
  - jupyterlab=1.1
  - matplotlib=3.1
  - numpy=1.16
  - pandas=0.25
  - psycopg2=2.8
  - scipy=1.3
  - sqlalchemy=1.3
