name: tufterati
channels:
  - default
  - anaconda
  - conda-forge
  - plotly
dependencies:
  - python=3.7.4
  - ipython=7.10
  - ipdb=0.12
  - pylint=2.4
  - pytest=5.3
  - airflow=1.10
  - dash=1.4
  - dash-daq=0.2
  - fbprophet=0.5
  - ipywidgets=7.5
  - jupyterlab=1.2
  - matplotlib=3.1
  - nodejs=10.13
  - numpy=1.17
  - pandas=0.25
  - plotly=4.4
  - plotly-orca=1.2
  - psutil=5.6
  - psycopg2=2.8
  - requests=2.22
  - scikit-learn=0.21
  - scipy=1.3
  - sqlalchemy=1.3
  - statsmodels=0.10
